apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-training

resources:
  - dspa.yaml
  # - minio.yaml

helmCharts:
  - name: minio
    releaseName: minio
    namespace: ai-example-training
    repo: https://charts.min.io/
    valuesInline:
      rootUser: minio
      rootPassword: minio123
