kind: ClusterPolicy
apiVersion: nvidia.com/v1
metadata:
  name: gpu-cluster-policy
spec:
  daemonsets:
    tolerations:
      - effect: NoSchedule
        key: nvidia-gpu-only
        operator: Exists
