apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    opendatahub.io/dashboard: "true"

resources:
  - ai-example-single-model-serving-namespace.yaml
  - create-bucket-job.yaml
  - serving-runtime.yaml
  - inference-service.yaml
