apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: false
  pairs:
    opendatahub.io/dashboard: "true"

resources:
  - service-account-demo-setup.yaml
  - cluster-role-binding-demo-setup.yaml
  - create-ds-connection-secret.yaml
  - create-bucket-job.yaml
