apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- wait-for-servicemesh-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-wait-for-servicemesh
    namespace: redhat-ods-operator
    files:
      - wait-for-servicemesh-job.sh
