---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-wait-for-servicemesh
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-wait-for-servicemesh
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-wait-for-servicemesh
  annotations:
    argocd.argoproj.io/hook: PreSync
subjects:
  - kind: ServiceAccount
    name: job-wait-for-servicemesh
    namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-wait-for-servicemesh
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-wait-for-servicemesh
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job-wait-for-servicemesh.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-wait-for-servicemesh
            defaultMode: 0755
      restartPolicy: Never
      serviceAccount: job-wait-for-servicemesh
      serviceAccountName: job-wait-for-servicemesh
  backoffLimit: 4
